spring:
  profiles:
    active: file

file:
  voucherResourcesPath: ./src/main/resources/voucherResources/
  consumerPath: ./src/main/resources/consumerResources/

db:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}