spring:
  profiles:
    active: jdbc

file:
  voucherResourcesPath: ./src/main/resources/voucherResources/
  consumerBlacklistPath: ./src/main/resources/consumerResources/

db:
  url: jdbc:mysql://localhost/voucherApplication
  user: root
  password: root1234!