spring:
  profiles:
    active: jdbc

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false

file:
  path:
  voucherResources: ./src/main/resources/voucherResources/
  consumer: ./src/main/resources/consumerResources/

db:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}